In [7]:

import numpy as np
from datetime import datetime
# File Path

file_path = r"C:\Users\vaish\Downloads\12721105-DADS_Minor_PROJECT_dataset\DADS Minor PROJECT dataset.txt"
with open(file_path, "r", encoding="utf-8") as file:
    lines = file.readlines()

print("Total Lines :", len(lines))
messages = []

participants = set()

system_count = 0

media_count = 0

deleted_count = 0
previous_message = None

for line in lines:

    line = line.strip()

    if line == "":
        continue

    
    if len(line) < 8 or line[2] != "/" or line[5] != "/":

        if previous_message is not None:

            previous_message["text"] += " " + line

        continue

    if " - " not in line:

        continue

    timestamp, remaining = line.split(" - ", 1)

    if ": " not in remaining:

        system_count += 1
        continue

    sender, text = remaining.split(": ", 1)

    participants.add(sender)

    if text == "<Media omitted>":

        media_count += 1

    elif text == "This message was deleted":

        deleted_count += 1

    message = {

        "timestamp": timestamp,
        "sender": sender,
        "text": text

    }

    messages.append(message)

    previous_message = message


print("Parsing Completed Successfully")



print("Total Parsed Messages :", len(messages))

print("Participants :", len(participants))

print("System Messages :", system_count)

print("Media Messages :", media_count)

print("Deleted Messages :", deleted_count)


print("\nFirst Five Messages\n")

for msg in messages[:5]:

    print(msg)
    print("\nLast Five Messages\n")

for msg in messages[-5:]:

    print(msg)

Total Lines : 3178
Parsing Completed Successfully
Total Parsed Messages : 3174
Participants : 6
System Messages : 4
Media Messages : 32
Deleted Messages : 15

First Five Messages

{'timestamp': '01/04/24, 01:17', 'sender': 'Rahul', 'text': 'scene fix'}

Last Five Messages

{'timestamp': '01/04/24, 01:17', 'sender': 'Rahul', 'text': 'haan'}

Last Five Messages

{'timestamp': '01/04/24, 01:18', 'sender': 'Rahul', 'text': 'kya scene'}

Last Five Messages

{'timestamp': '01/04/24, 02:13', 'sender': 'Rahul', 'text': 'abhi free hai?'}

Last Five Messages

{'timestamp': '01/04/24, 02:13', 'sender': 'Rahul', 'text': 'abey'}

Last Five Messages

{'timestamp': '30/05/24, 19:14', 'sender': 'Priya', 'text': 'Take care everyone'}
{'timestamp': '30/05/24, 19:28', 'sender': 'Priya', 'text': 'Karan that sounds tough, take care'}
{'timestamp': '30/05/24, 21:17', 'sender': 'Aman', 'text': 'the existential dread is back'}
{'timestamp': '30/05/24, 21:30', 'sender': 'Karan', 'text': 'Long day guys, woke up

In [8]:
total_messages = len(messages)

print("Total Messages :", total_messages)

total_participants = len(participants)

print("Participants :", total_participants)

first_date = datetime.strptime(messages[0]["timestamp"], "%d/%m/%y, %H:%M")
last_date = datetime.strptime(messages[-1]["timestamp"], "%d/%m/%y, %H:%M")

print("Start Date :", first_date.strftime("%d %B %Y"))
print("End Date   :", last_date.strftime("%d %B %Y"))

total_days = (last_date - first_date).days + 1

print("Total Days :", total_days)

message_count = {}

for msg in messages:

    sender = msg["sender"]

    if sender in message_count:

        message_count[sender] += 1

    else:

        message_count[sender] = 1

sorted_people = sorted(
    message_count.items(),
    key=lambda x: x[1],
    reverse=True
)
print("=" * 60)
print("GROUP OVERVIEW")
print("=" * 60)

print(f"Group Name      : Hostel Bois 4ever")
print(f"Period          : {first_date.strftime('%d %B %Y')} to {last_date.strftime('%d %B %Y')}")
print(f"Duration        : {total_days} Days")
print(f"Total Messages  : {total_messages}")
print(f"Participants    : {total_participants}")

print("=" * 60)
print("MESSAGES PER PERSON")
print("=" * 60)

for person, count in sorted_people:

    percentage = (count / total_messages) * 100

    print(f"{person:<10} {count:>5} ({percentage:.1f}%)")
    



Total Messages : 3174
Participants : 6
Start Date : 01 April 2024
End Date   : 30 May 2024
Total Days : 60
GROUP OVERVIEW
Group Name      : Hostel Bois 4ever
Period          : 01 April 2024 to 30 May 2024
Duration        : 60 Days
Total Messages  : 3174
Participants    : 6
MESSAGES PER PERSON
Rahul        953 (30.0%)
Priya        718 (22.6%)
Neha         635 (20.0%)
Aman         490 (15.4%)
Karan        354 (11.2%)
Vikas         24 (0.8%)


In [9]:


day_count = {}

for msg in messages:

    date = msg["timestamp"].split(",")[0]

    if date in day_count:
        day_count[date] += 1
    else:
        day_count[date] = 1
 
busiest_day = max(day_count, key=day_count.get)

busiest_day_messages = day_count[busiest_day]

formatted_day = datetime.strptime(
    busiest_day,
    "%d/%m/%y"
).strftime("%d %B %Y")

hour_count = {}

for hour in range(24):
    hour_count[hour] = 0

for msg in messages:

    time = msg["timestamp"].split(", ")[1]

    hour = int(time.split(":")[0])

    hour_count[hour] += 1

busiest_hour = max(hour_count, key=hour_count.get)

busiest_hour_messages = hour_count[busiest_hour]

next_hour = (busiest_hour + 1) % 24
print("=" * 60)
print("MOST ACTIVE TIME")
print("=" * 60)

print(
    f"Busiest Day  : {formatted_day} ({busiest_day_messages} messages)"
)

print(
    f"Busiest Hour : {busiest_hour:02d}:00 - {next_hour:02d}:00 ({busiest_hour_messages} messages)"
)

print("=" * 60)
print("\nMESSAGES BY HOUR")
print("=" * 60)

for hour in range(24):

    next_hour = (hour + 1) % 24

    print(
        f"{hour:02d}:00 - {next_hour:02d}:00 : {hour_count[hour]}"
    )
    


    


MOST ACTIVE TIME
Busiest Day  : 04 May 2024 (76 messages)
Busiest Hour : 18:00 - 19:00 (248 messages)

MESSAGES BY HOUR
00:00 - 01:00 : 57
01:00 - 02:00 : 82
02:00 - 03:00 : 83
03:00 - 04:00 : 77
04:00 - 05:00 : 110
05:00 - 06:00 : 29
06:00 - 07:00 : 33
07:00 - 08:00 : 55
08:00 - 09:00 : 122
09:00 - 10:00 : 151
10:00 - 11:00 : 160
11:00 - 12:00 : 114
12:00 - 13:00 : 193
13:00 - 14:00 : 159
14:00 - 15:00 : 162
15:00 - 16:00 : 131
16:00 - 17:00 : 189
17:00 - 18:00 : 173
18:00 - 19:00 : 248
19:00 - 20:00 : 228
20:00 - 21:00 : 166
21:00 - 22:00 : 177
22:00 - 23:00 : 116
23:00 - 00:00 : 159


In [10]:


people = sorted(list(participants))

print("Participants:")

for person in people:
    print(person)

person_index = {}

for i in range(len(people)):
    person_index[people[i]] = i

print(person_index)

heatmap = np.zeros((len(people), 24), dtype=int)

print(heatmap)

for msg in messages:

    sender = msg["sender"]

    row = person_index[sender]

    time = msg["timestamp"].split(", ")[1]

    hour = int(time.split(":")[0])

    heatmap[row][hour] += 1
print("Heatmap Matrix")

print(heatmap)
print("=" * 90)
print("ACTIVITY HEATMAP")
print("=" * 90)

print("Name       ", end="")

for hour in range(24):
    print(f"{hour:02d} ", end="")

print()
for i in range(len(people)):

    print(f"{people[i]:<10}", end=" ")

    maximum = heatmap[i].max()

    if maximum == 0:
        maximum = 1

    for value in heatmap[i]:

        ratio = value / maximum

        if ratio == 0:
            symbol = ". "

        elif ratio <= 0.25:
            symbol = "░ "

        elif ratio <= 0.50:
            symbol = "▒ "

        else:
            symbol = "█ "

        print(symbol, end="")

    print()
    print("\n")

print("=" * 60)

print("TOTAL MESSAGES FROM MATRIX")

print("=" * 60)

for i in range(len(people)):

    total = np.sum(heatmap[i])

    print(f"{people[i]:<10} {total}")

    



Participants:
Aman
Karan
Neha
Priya
Rahul
Vikas
{'Aman': 0, 'Karan': 1, 'Neha': 2, 'Priya': 3, 'Rahul': 4, 'Vikas': 5}
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Heatmap Matrix
[[ 54  67  66  60  88   0   0   0   0   0   0   0   0   0  14  11  19   7
   16   8  13  11   0  56]
 [  0   0   0   0   0   0   0   4  12  16  20  16  37  25  32  27  27  27
   25  32  23  14   9   8]
 [  0   0   0   0   0  19   3  13  36  52  52  22  39  36  27  10  37  47
   62  50  45  27  28  30]
 [  0   0   0   0   0   0  13  20  47  65  62  61  57  48  44  29  32  40
   38  60  43  32  18   9]
 [  3  15  17  17  22  10  17  17  24  17  25  15  58  48  45  53  73  49
  105  76  41  92  60  54]
 [  0   0   0   0   0   0   0   1   3   1   1   0   2 

In [11]:


stop_words = [

    "i","is","the","a","an","and","or","to","of","in",
    "on","for","at","it","its","it's","are","am","was",
    "were","be","been","being","you","me","my","we",
    "our","your","this","that","with","from","as","if",
    "but","so","do","does","did"

]

punctuation = ".,!?;:()[]{}<>\"'`-_/\\|@#$%^&*+=~"

word_count = {}

for msg in messages:

    text = msg["text"]

    # Ignore media
    if text == "<Media omitted>":
        continue

    # Ignore deleted messages
    if text == "This message was deleted":
        continue

    words = text.split()

    for word in words:

        word = word.lower()

        word = word.strip(punctuation)

        if word == "":
            continue

        if word in stop_words:
            continue

        if word in word_count:

            word_count[word] += 1

        else:

            word_count[word] = 1

top_words = sorted(

    word_count.items(),

    key=lambda x: x[1],

    reverse=True

)

print("=" * 70)

print("THIS GROUP'S FAVOURITE WORDS")

print("=" * 70)

maximum = top_words[0][1]

for word, count in top_words[:10]:

    bar = "█" * int((count / maximum) * 25)

    print(f"{word:<15} {bar:<25} {count}")    
    


THIS GROUP'S FAVOURITE WORDS
how             █████████████████████████ 321
guys            ████████████████████████  318
about           █████████████████████     274
hai             ████████████████████      268
today           ████████████████████      257
he              █████████████████         220
his             ████████████████          217
have            ████████████████          209
just            ████████████████          208
which           ███████████████           202
